config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
                  path("", TemplateView.as_view(template_name="index.html"), name="home"),
                  path(
                      "about/",
                      TemplateView.as_view(template_name="pages/about.html"),
                      name="about",
                  ),
                  # Django Admin, use {% url 'admin:index' %}
                  path(settings.ADMIN_URL, admin.site.urls),
                  # User management
                  path(
                      "users/",
                      include("qa_moderator.users.urls", namespace="users"),
                  ),
                  path("accounts/", include("allauth.urls")),
                  path("questions/", include("qa_moderator.questions.urls", namespace='questions')),
                  path("polls/", include("qa_moderator.polls.urls", namespace='polls')),
                  path("questions/api/v1/", include("qa_moderator.questions.api.urls", namespace='questions-api')),
                  path("events/api/v1/", include("qa_moderator.events.api.urls", namespace='events-api')),
                  path("core/api/v1/", include("qa_moderator.core.api.urls", namespace='core-api')),
                  # Your stuff: custom urls includes go here
              ] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

qa_moderator/polls/urls.py
from django.urls import path
from django.views.generic import TemplateView

from qa_moderator.polls.views import PollView

app_name = "polls"
urlpatterns = [
    # ...
    path('answer/<int:pk>/', PollView.as_view(), name='poll-view'),
    path("thanks/", view=TemplateView.as_view(template_name="polls/thanx.html"), name="poll-thanks"),
]

qa_moderator/questions/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import create_question_view, questions_display_view

app_name = "questions"
urlpatterns = [
    path("", view=create_question_view, name="create-question"),
    path("<int:event_pk>/", view=create_question_view, name="create-question-event"),
    path("thanks/", view=TemplateView.as_view(template_name="questions/thanx.html"), name="thanks"),
    path("schedule/", view=TemplateView.as_view(template_name="questions/schedule.html"), name="schedule"),
    path("countdown/", view=TemplateView.as_view(template_name="questions/countdown.html"), name="countdown"),
    path("qrcloud/", view=TemplateView.as_view(template_name="questions/qrcloud.html"), name="qrcloud"),
    path("qrquestions/", view=TemplateView.as_view(template_name="questions/qrquestions.html"), name="qrquestions"),
    path("display/", view=questions_display_view, name="display"),

]

qa_moderator/users/urls.py
from django.urls import path

from qa_moderator.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

qa_moderator/events/models.py
from django.db import models

# Create your models here.
from model_utils.models import TimeStampedModel
from django.utils.translation import ugettext_lazy as _

class Event(TimeStampedModel):

    name = models.CharField(_('name'), max_length=60)
    title = models.CharField(_('title'), max_length=60)
    event_date = models.DateField(_('event date'))
    office_name = models.CharField(_('office name'), max_length=80)
    fiscal_year = models.IntegerField(_('fiscal year'))
    start_availability = models.DateTimeField(_('start availability'), null=True)
    end_availability = models.DateTimeField(_('end availability'), null=True)
    active = models.BooleanField(_('active'), default=True)

    def __str__(self):
        return self.name

qa_moderator/polls/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
# Create your models here.
from model_utils.models import TimeStampedModel


class Poll(TimeStampedModel):
    text = models.CharField(max_length=255)
    pub_date = models.DateField()

    def __str__(self):
        return self.text


class Question(TimeStampedModel):
    poll = models.ForeignKey(Poll, verbose_name=_('poll'), related_name='questions', on_delete=models.CASCADE)
    content = models.TextField(_('content'))

    def __str__(self):
        return self.content


class Choice(TimeStampedModel):
    question = models.ForeignKey(Question, verbose_name=_('question'), related_name='choices', on_delete=models.CASCADE)
    value = models.CharField(_('value'), max_length=125)
    numeric_value = models.IntegerField(_('numeric value'), default=0)

    def __str__(self):
        return self.value


class Answer(TimeStampedModel):
    question = models.ForeignKey(Question, verbose_name=_('question'), related_name='answers',
                                 on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, verbose_name=_('choice'),
                               related_name='answers',
                               on_delete=models.CASCADE,
                               null=True)
    content = models.CharField(_('content'), max_length=255, null=True)

    def __str__(self):
        if self.choice is not None:
            return self.choice.value
        elif self.content is not None:
            return self.content
        else:
            return '?????'

qa_moderator/questions/models.py
from django.db import models

# Create your models here.
from model_utils.models import TimeStampedModel
from simple_history.models import HistoricalRecords

from qa_moderator.events.models import Event


class Question(TimeStampedModel):
    approved = models.BooleanField(default=False,
                                   help_text='Is approved to be displayed')
    viewed = models.BooleanField(default=False,
                                 help_text='Has already been displayed')
    priority = models.IntegerField(default=10000,
                                   help_text='Order to display questions. Lower '
                                             'number has higher priority and will be displayed first'
                                   )
    question = models.TextField()
    moderator_num = models.IntegerField(default=0,
                                        help_text='Field to separate questions '
                                                  'between moderators. Zero means not assigned')
    event = models.ForeignKey(Event, verbose_name='event', related_name='questions',
                              null=True, on_delete=models.CASCADE)
    history = HistoricalRecords()

    def __str__(self):
        return self.question

qa_moderator/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

qa_moderator/questions/forms.py
from django import forms
from django.conf import settings

from qa_moderator.questions.models import Question


class QuestionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        self.fields['moderator_num'].widget = forms.HiddenInput()
        self.fields['event'].widget = forms.HiddenInput()

    class Meta:
        model = Question
        fields = ['id', 'question', 'moderator_num', 'event']

    def save(self, commit=True):
        max_num_moderators = settings.QUESTIONS_MAX_MODERATORS_NUM
        question_data = self.cleaned_data
        current_moderator = 1
        if Question.objects.count() > 0:
            last_question_moderator = Question.objects.last().moderator_num
            current_moderator = last_question_moderator + 1
            if current_moderator > max_num_moderators:
                current_moderator = 1
        question_data['moderator_num'] = current_moderator
        question = Question.objects.create(**question_data)
        return question

qa_moderator/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

qa_moderator/core/api/views.py
from django.http import JsonResponse

import qa_moderator


def app_info(request):
    app_info = dict()
    app_info['version'] = qa_moderator.__version__
    return JsonResponse(app_info)

qa_moderator/events/api/views.py
from rest_framework.generics import ListAPIView, RetrieveUpdateDestroyAPIView, CreateAPIView

from .serializers import EventSerializer
from ..models import Event

class EventListAPIView(ListAPIView):
    serializer_class = EventSerializer

    def get_queryset(self):
        return Event.objects.all()


class EventDetailAPIView(RetrieveUpdateDestroyAPIView):
    serializer_class = EventSerializer
    queryset = Event.objects.all()

    def get_object(self):
        return super(EventDetailAPIView, self).get_object()


class EventCreateAPIView(CreateAPIView):
    serializer_class = EventSerializer

qa_moderator/events/views.py
from django.shortcuts import render

# Create your views here.

qa_moderator/polls/views.py
import re

from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import UpdateView

from qa_moderator.polls.models import Poll, Question, Choice, Answer


class PollView(UpdateView):
    model = Poll
    fields = ['text']

    def get(self, request, *args, **kwargs):
        response = super(PollView, self).get(request, *args, **kwargs)
        if 'filled_poll_rci_2019' in request.COOKIES:
            return HttpResponseRedirect('/polls/thanks/')

        return response


    def post(self, request, *args, **kwargs):
        ip_address = request.META.get('HTTP_X_FORWARDED_FOR', '') or request.META.get('REMOTE_ADDR')

        regexp = re.compile(r'^answer_(\d+)$')
        for key, data in request.POST.items():
            match = regexp.match(key)
            if match:
                question_id = int(match.group(1))
                question = Question.objects.get(pk=question_id)
                choice_id = int(data)
                choice = Choice.objects.get(pk=choice_id)
                answer = Answer.objects.create(question=question, choice=choice, content=choice.value)

        response = HttpResponseRedirect('/polls/thanks/')
        response.set_cookie('filled_poll_rci_2019', ip_address)
        return response

qa_moderator/questions/api/views.py
from rest_framework.generics import ListAPIView, RetrieveUpdateDestroyAPIView, CreateAPIView

from .serializers import QuestionSerializer, QuestionWriteSerializer
from ..models import Question


class QuestionListAPIView(ListAPIView):
    serializer_class = QuestionSerializer

    def get_queryset(self):
        qs = Question.objects.filter(approved=True, viewed=False).order_by('priority')
        return qs


class QuestionDetailAPIView(RetrieveUpdateDestroyAPIView):
    serializer_class = QuestionSerializer
    queryset = Question.objects.all()

    def get_object(self):
        return super(QuestionDetailAPIView, self).get_object()


class QuestionCreateAPIView(CreateAPIView):
    serializer_class = QuestionWriteSerializer

qa_moderator/questions/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from qa_moderator.events.models import Event
from qa_moderator.questions.forms import QuestionForm
from qa_moderator.questions.models import Question


class CreateQuestionView(CreateView):
    model = Question
    success_url = reverse_lazy('questions:thanks')
    #fields = ('id', 'question')
    form_class = QuestionForm

    def get_template_names(self):
        return ['questions/question.html']
        #if settings.QUESTIONS_ACTIVE:
           # return ['questions/question.html']
        # else:
          #  return ['questions/countdown.html']

    def post(self, request, *args, **kwargs):
        post_data = dict()
        post_data['question'] = request.POST['question']
        try:
            event = Event.objects.get(id=self.kwargs.get('event_pk'))
            post_data['event'] = event
        except Event.DoesNotExist as e:
            raise e
        form = QuestionForm(data=post_data)
        if form.is_valid():
            form.save()
            redirect(self.success_url)
        else:
            return None
        #return super(CreateQuestionView, self).post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CreateQuestionView, self).get_context_data(**kwargs)
        try:
            event = Event.objects.get(id=self.kwargs.get('event_pk'))
            title = event.title
        except Event.DoesNotExist:
            title = 'No Event for {} event id'.format(self.kwargs.get('event_pk'))

        context['title'] = title
        return context



create_question_view = CreateQuestionView.as_view()


class QuestionsDisplayView(LoginRequiredMixin, TemplateView):

    def get_template_names(self):
        return ['questions/display.html']


questions_display_view = QuestionsDisplayView.as_view()

qa_moderator/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

qa_moderator/templates/questions/countdown.html
{% extends "_base.html" %}
{% load static i18n %}
{% block extra_css %}
    <link href="{% static 'css/schedule.css' %}" rel="stylesheet">
{% endblock extra_css %}
{% block content %}

  <div class="row">
    <div class="col-md-12">
      <div id="countdown">
			<div id="countdowndays" class="box"><p></p></div>
			<div id="countdownhours" class="box"><p></p></div>
			<div id="countdownmins" class="box"><p></p></div>
			<div id="countdownsecs" class="box"><p></p></div>
        </div>
    </div>
    <!--/col-->
  </div>
  <!--/row-->


{% endblock content %}

  {% block extra_js %}
<script src="{% static 'js/countdown.js' %}"></script>
  {% endblock extra_js %}

qa_moderator/templates/questions/display.html
{% extends "_base.html" %}
{% load static i18n %}

  {% block extra_css %}
    <link href="{% static 'css/display.css' %}" rel="stylesheet">

  {% endblock extra_css %}

{% block content %}
    <div class="row">
            <div class="col-md-12 mx-auto">
                <div class="slider">
                    <ul class="slider-list">
                    </ul>
                </div>
            </div>
        </div>


    <script type="text/javascript" text="javascript">
        $.getJSON("../api/", function (data) {
            var myJson = data.results;
            var lastItem = data.count;
            for (var i = 0; i < lastItem; i++) {
                $('.innerCarousel').css('width', (lastItem * 500) + 'px');
                $('.slider-list').append('<li><div class="chepe"><div class="chepe2">' + myJson[i].question + '</div> </div></li>');
            }


            // Allow for muclitple sliders by running the code on each of them
            $('.slider').each(function () {
                // Set up vars
                var $slider = $(this),
                    $sliderList = $slider.find('.slider-list'),
                    slides = $sliderList.children().length,
                    currentSlide = 0;

                // Append slider nav
                $slider.append('<button class="slider-nav slider-prev"><<</button><button class="slider-nav slider-next">>></button>');
                var $sliderNav = $slider.find('.slider-nav');

                // Add active class to first slide
                $sliderList.children().first().addClass('active-slide');
                var slideHeight = $sliderList.find('.active-slide').outerHeight();

                $slider.css('height', slideHeight);

                $sliderNav.on('click', function () {
                    $(this).closest('.slider').find('.active-slide').removeClass('active-slide');

                    if ($(this).is('.slider-next')) {
                        _nextSlide();
                    }

                    if ($(this).is('.slider-prev')) {
                        _prevSlide();
                    }

                    $(this).closest('.slider').find('li:eq(' + currentSlide + ')').addClass('active-slide');
                    slideHeight = $sliderList.find('.active-slide').outerHeight();
                    $slider.animate({
                        'height': slideHeight
                    }, 150);
                });

                function _nextSlide() {
                    currentSlide++;
                    if (currentSlide == slides) {
                        currentSlide = 0;
                    }
                    var slideLength = 100 * currentSlide;
                    $sliderList.css('transform', 'translateX(-' + slideLength + '%)');
                }

                function _prevSlide() {
                    currentSlide--;
                    if (currentSlide < 0) {
                        currentSlide = slides - 1;
                    }
                    var slideLength = 100 * currentSlide;
                    $sliderList.css('transform', 'translateX(-' + slideLength + '%)');
                }
            });


        });

    </script>
{% endblock content %}

qa_moderator/templates/questions/home.html
{% extends "_base.html" %}
{% load static i18n %}

{% block content %}

{% comment %}    <div class="row">
        <div class="col-md-12">
            <div class="home-image-body">
                <div id="main" class="home-image-container">
                    <img src="{% static 'images/rci_ists.jpg' %}"/>
                    <img src="{% static 'images/rci_ists.jpg' %}"/>
                    <img src="{% static 'images/rci_ists.jpg' %}"/>
                    <img src="{% static 'images/rci_ists.jpg' %}"/>
                </div>
            </div>
        </div>{% endcomment %}
        <div class="col-md-12 version-content">
            <a class="btn btn-success btn-lg text-center" href="{% url 'questions:create-question' %}">New
                Question ?</a>
            <a class="btn btn-success btn-lg text-center" href="{% url 'questions:display' %}">Display
                Questions</a>
        </div>
        <!--/col-->
    </div>
    <!--/row-->




{% endblock content %}

qa_moderator/templates/questions/qrcloud.html
{% extends "_base.html" %}
{% load static i18n %}

{% block content %}


  <!--/col-->
  <div class="row">
    <div class="col-md-4 col align-self-center">
      <h1>Nube de Palabras</h1>
    </div>
    <div class="col-md-8">
      <img src="{% static 'images/qr_word_cloud.png' %}" class="" alt="...">
    </div>
  </div>


  <div class="row">
    <div class="col-md-12">
      <span class="qr-url">URL: https://www.menti.com/</span>
    </div>
  <div class="col-md-12">
      <span class="qr-url">Código: 75 25 08</span>
    </div>

  </div>

  <!--/col-->
  <!--/row-->


{% endblock content %}

qa_moderator/templates/questions/qrquestions.html
{% extends "_base.html" %}
{% load static i18n %}

{% block content %}

  <div class="row">
    <div class="col-md-4 col align-self-center">
      <h1>Preguntas y Respuestas</h1>
    </div>
    <div class="col-md-8">
      <img src="{% static 'images/qr_questions.png' %}" class="" alt="...">
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col align-self-center">
      <span class="qr-url">URL: https://rci-ist.herokuapp.com/questions/</span>
    </div>
  </div>

  <!--/row-->

  <!--/col-->
  <!--/row-->


{% endblock content %}

qa_moderator/templates/questions/question.html
{% extends "_base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block content %}

            <h2>{{ title }}</h2>
            <div class="row">
                <div class="col-md-8 col-11 mx-auto">

                    <!-- form card login -->
                    <div class="card rounded-0">
                        <div class="card-header">
                            <h3 class="mb-0">Q&A</h3>
                        </div>
                        <div class="card-body">

                            <form class="form" role="form" autocomplete="off" id="formLogin" novalidate=""
                                  method="POST">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button type="submit" class="btn btn-success btn-lg float-right" id="btnLogin">Submit
                                </button>
                            </form>
                        </div>
                        <!--/card-block-->
                    </div>
                    <!-- /form card login -->

                </div>


            </div>
            <!--/row-->



{% endblock content %}

qa_moderator/templates/questions/schedule.html
{% extends "_base.html" %}
{% load static i18n %}
{% block extra_css %}
    <link href="{% static 'css/schedule.css' %}" rel="stylesheet">
{% endblock extra_css %}
{% block content %}

    <div class="row">
        <div class="col-md-12 schedule-table table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    {% comment %} <th scope="col">Horario</th>
                    <th scope="col">Tiempo</th>{% endcomment %}
                    <th scope="col">Actividad</th>
                    <th scope="col">Responsable</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">1</th>
                    {% comment %} <td>07:00 – 07:45</td>
                    <td>45 mins</td>{% endcomment %}
                    <td>Desayuno – Ala Gerencial</td>
                    <td></td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    {% comment %} <td>07:45 – 08:15</td>
                    <td>30 mins</td>{% endcomment %}
                    <td>Bienvenida,
                        Introducción de herramienta de comunicación
                    </td>
                    <td>Maribel Rodríguez,
                        Rafael Batista
                    </td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    {% comment %} <td>07:45 – 08:15</td>
                    <td>30 mins</td>{% endcomment %}
                    <td>Tecnología e Informática:
                        Visión y Planificación 2019
                    </td>
                    <td>Vielka Arthur</td>
                </tr>
                <tr>
                    <th scope="row">4</th>
                    {% comment %}  <td>08:15 - 08:45</td>
                    <td>30 mins</td>{% endcomment %}
                    <td>MS Office 365 –
                        Herramientas de Colaboración </td>
                    <td>Juan Francisco Escobar, Microsoft</td>
                </tr>
                <tr>
                    <th scope="row"></th>
                    {% comment %} <td>08:45 – 08:50</td>
                    <td>5 mins</td>{% endcomment %}
                    <td>Negocios Complementarios</td>
                    <td>Antonio Michel</td>
                </tr>
                <tr>
                    <th scope="row">5</th>
                    {% comment %}<td>08:50 - 09:10</td>
                    <td>20 minss</td>{% endcomment %}
                    <td>Negocio de Telecomunicaciones</td>
                    <td>Germán Espinosa</td>
                </tr>
                <tr>
                    <th scope="row">6</th>
                    {% comment %} <td>09:10 - 09:25</td>
                    <td>15 mins</td>{% endcomment %}
                    <td>Negocio de Turismo</td>
                    <td>Maria G. Ávila</td>
                </tr>
                <tr>
                    <th scope="row">7</th>
                    {% comment %} <td>09:25 - 09:35</td>
                    <td>10 mins</td>{% endcomment %}
                    <td>La Ciberseguridad y
                        la Transformación Digital
                    </td>
                    <td>Edwin Reina</td>
                </tr>
                <tr>
                    <th scope="row">8</th>
                    {% comment %} <td>09:35 – 9:55</td>
                    <td>20 mins</td>{% endcomment %}
                    <td>Reconocimientos</td>
                    <td>Los gerentes IST</td>
                </tr>
                <tr>
                    <th scope="row">9</th>
                    {% comment %} <td>09:55 - 10:40</td>
                    <td>45 mins</td>{% endcomment %}
                    <td>Panel “Creando Futuro”</td>
                    <td><strong>Moderador:</strong>
                        Maribel Rodríguez
                    </br>
                        <strong>
                            Integrantes:</strong>
                        Angie Hanily,
                        Vielka Arthur,
                        Leyla Raymondo,
                        Cristina Lee,
                        Antonio Michel
                    </td>
                </tr>
                <tr>
                    <th scope="row">10</th>
                    {% comment %}  <td>10:40 – 11:25</td>
                    <td>45 mins</td>{% endcomment %}
                    <td>Una nueva mirada hacia el futuro</td>
                    <td>Ely Aquino y
                        Roberto Bernal
                    </td>
                </tr>
                <tr>
                    <th scope="row">11</th>
                    {% comment %}   <td>11:25 – 11:35</td>
                    <td>10 mins</td>{% endcomment %}
                    <td>Visión del VP de Ingeniería y Servicios
                    </td>
                    <td>Miguel Lorenzo</td>
                </tr>
                <tr>
                    <th scope="row">12</th>
                    {% comment %}   <td>11:25 – 11:35</td>
                    <td>10 mins</td>{% endcomment %}
                    <td>Agradecimiento y Cierre
                    </td>
                    <td>Vielka Arthur,
                        Maribel Rodríguez,
                        Rafael Batista
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <!--/col-->
    </div>
    <!--/row-->
{% endblock content %}

qa_moderator/templates/questions/thanx.html
{% extends "_base.html" %}
{% load static i18n %}

{% block content %}

  <div class="row">
    <div class="col-md-12">
      <h2 class="text-center text-white mb-4">Thank you</h2>

        <div class="col-md-8 mx-auto">
          <div class="card-body">
            <form action="" method="get">
              <a class="btn btn-success btn-lg text-center" href="{% url 'questions:create-question' %}">New
                Question</a>
            </form>
          </div>
      </div>
    </div>
    <!--/col-->
  </div>
  <!--/row-->


{% endblock content %}